wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.32
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.8
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 1
      - 2
      4: 3.8.8
      5: 0.10.32
      8:
      - 5
k:
  desc: null
  value: 24
lr:
  desc: null
  value: 0.001
lr_rate:
  desc: null
  value: 0.2
ratio1:
  desc: null
  value: 10
ratio2:
  desc: null
  value: 0.1
sig_max:
  desc: null
  value: 10
sig_min:
  desc: null
  value: 1
wd:
  desc: null
  value: 1.0e-06
